### ISSUE TITLE
Firefox - when I click a link it takes few seconds before a request is sent

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkusio.github.io#209]
When I click a link it takes few seconds before a request is sent. Most probably some JS tracing stuff? I'm using Firefox 67.0. I don't observe this behavior when using Chromium 73.

**Comment by mkouba** [comment]
@emmanuelbernard how can I increase the priority of this issue? It's really annoying and I'm probably not the only dev using Firefox. And there was at least one more guy mentioning this problem on zulip ;-)

**Comment by emmanuelbernard** [comment]
@adelasofia could you try and figure that one out? To be fair I don't see that experience on macOS + Firefox. Which OS @mkouba ?

**Comment by mkouba** [comment]
I'm on Linux. If needed I can try to figure out... but I have no idea where to start. It could be some DNS issue too.

**Comment by mkouba** [comment]
So I found out that it's caused by [Firefox Content blocking](https://support.mozilla.org/en-US/kb/content-blocking), namely when "Trackers" blocking is enabled for all windows. When I disable this feature everything works just fine.

I can see that the following scripts were blocked:
- https://assets.adobedtm.com/2b327a0a54b320bf1bcdb5fa39a2b896027067d9/s-code-contents-31c4c9d0810efb8149b11b12fc8b69f91c220862.js
- https://assets.adobedtm.com/2b327a0a54b320bf1bcdb5fa39a2b896027067d9/scripts/satellite-59a09d8264746d6e3a0059d1.js
- https://www.google-analytics.com/analytics.js

I do agree that most users probably don't block trackers but it would be nice if the site works smoothly even without the trackers.

**Comment by FroMage** [comment]
> Totally. More and more people do that nowadays, and it should be simple to fix.

**Comment by jkbrock** [comment]
@FroMage and @mkouba, would you mind looking again to see if you're still having this issue? I'm using Firefox 67.0.4 on a Mac and seeing zero issues with load time, even with the content blocker enabled. Everything is loading in under 0.5sec

**Comment by mkouba** [comment]
Hey @jkbrock, I can still observe the issue when I enable content blocking - Ubuntu, Firefox 68.0.

**Comment by emmanuelbernard** [comment]
@jkbrock I also see the issue. Make sure to *not have* uBlock Origin or disable it for the Quarkus pages.

**Comment by stdunbar** [comment]
Note the virtually all RedHat sites have this issue - wildfly.org works just a poorly.

**Comment by jpkrohling** [comment]
For the record, such blocking is now the default behavior in Firefox. More and more users are experiencing now.

**Comment by FroMage** [comment]
OK, lemme look at it.

**Comment by FroMage** [comment]
I can reproduce on FF.

**Comment by FroMage** [comment]
I think it may be a red herring: this actually only slows down clicking, not loading pages.

**Comment by FroMage** [comment]
It's `goan.js`: if I comment it out, we can click normally.

**Comment by FroMage** [comment]
So it's Google Analytics tracking clicks. We could disable click tracking in GA. What's the use-case?

**Comment by FroMage** [comment]
We're following this up with our GA admin. Hopefully we get this fixed ASAP.

**Comment by maxandersen** [comment]
its pretty useful to see which links on each page are actually used/found.

i.e. i looked at stats for publication page and can see which are mostly followed.
similar with user guides docs  - interesting to see links you thought everyone would use aren't used and vice versa.

isn't there a way to dynamically detect if browser is content blocking and then toggle it on/off ? so its still useful for us but fast no matter if you block or not ?

**Comment by jkbrock** [comment]
IIRC, we found that it had to do with a timing trigger in Google Analytics. We corrected the setting and were no longer able to replicate the issue.

**Comment by gastaldi** [comment]
@mkouba @FroMage can any of you confirm this is no longer happening and close this issue if possible?

Thanks!

**Comment by mkouba** [comment]
It seems that the problem is fixed (tested on firefox 89.0.2). Closing this issue...

**Comment by jpkrohling** [comment]
This is still happening for me.

![image](https://user-images.githubusercontent.com/13387/124245176-0688d800-db20-11eb-87d8-a34ecf4c05b8.png)

It takes about 2 seconds from clicking on "Learn more about 2.0" to the second event, which is the actual GET for /quarkus2.

**Comment by mkouba** [comment]
@jpkrohling Hm, what version of firefox? What's interesting that the domain `quarkus.io` is not secured for the `/quarkus2/` request. Could you try to clear the browser cache?

**Comment by jpkrohling** [comment]
That's 89.0 (64-bit) on Fedora 34. The same happens with a clear cache and by hitting https manually.
